[providers]
go = "1.23"

[phases.setup]
nixPkgs = ["go_1_23"]
nixLibs = []

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -o bin/main src/main.go"]

[start]
cmd = "./bin/main"
